### PR TITLE
fdimf

### LINKED ISSUE #47: implement fdimf
Source: https://git.musl-libc.org/cgit/musl/tree/src/math/fdimf.c

### PR DESCRIPTION
**Pull request by jackmott**
closes #47

### CODE REVIEW

**Comment by jackmott** [comment]
I've also removed the isnanf function and use core::f32/v64 is_nan() instead

**Comment by japaric** [comment]
LGTM but needs to be rebased. After rebasing please leave a comment with the text "bors r=japaric" without the quotes to put this in [the bors queue](https://app.bors.tech/repositories/2772).

bors delegate+

**Comment by jackmott** [comment]
bors r=japaric

**Pull request merged**
