### PR TITLE
implement ceil

### LINKED ISSUE #53: implement ceil
Source: https://git.musl-libc.org/cgit/musl/tree/src/math/ceil.c

### PR DESCRIPTION
**Pull request by lucasmarqs**
closes #53

### CODE REVIEW

**Comment by lucasmarqs** [comment]
@japaric done! 👍

**Comment by japaric** [comment]
https://travis-ci.org/japaric/libm/jobs/403814664#L485

As of #78 you need to run cargo fmt locally before submitting a PR.

**Pull request merged**
